"""Reorganiza tabela pedidos

Revision ID: 1dc1ecd24ea9
Revises: 4a0071c36628
Create Date: 2026-07-22 11:10:00.551157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc1ecd24ea9'
down_revision = '4a0071c36628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('taxa_entrega', sa.Float(), nullable=True))
        batch_op.drop_column('taca_entrega')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('taca_entrega', sa.FLOAT(), nullable=True))
        batch_op.drop_column('taxa_entrega')
        batch_op.drop_column('celular')

    # ### end Alembic commands ###
