"""atualizando store

Revision ID: 1ff2b7958335
Revises: 2084b6e0f388
Create Date: 2026-06-15 22:11:30.349239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff2b7958335'
down_revision = '2084b6e0f388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('rua', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bairro', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('celularp',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=18),
               nullable=False)
        batch_op.alter_column('nomedaloja',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('nomedaloja',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('celularp',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('rua')
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
