"""estrutura inicial

Revision ID: 2084b6e0f388
Revises: 
Create Date: 2026-06-15 21:55:13.225140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2084b6e0f388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celularp', sa.Integer(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('nomedaloja', sa.String(), nullable=True),
    sa.Column('nextreferencia', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('itens', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('nome_produto', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_carrinho')
    op.drop_table('produto')
    op.drop_table('pedidos')
    op.drop_table('carrinho')
    op.drop_table('user')
    op.drop_table('store')
    # ### end Alembic commands ###
