"""create new table for our pedidos database

Revision ID: 4a0071c36628
Revises: 1ff2b7958335
Create Date: 2026-07-22 10:52:42.093732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0071c36628'
down_revision = '1ff2b7958335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taca_entrega', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distancia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_entre_distancia', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('data_recebido', sa.DateTime(), nullable=True))
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('data_recebido')
        batch_op.drop_column('tempo_entre_distancia')
        batch_op.drop_column('distancia')
        batch_op.drop_column('taca_entrega')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
