"""Criando tabela pedidos novamente

Revision ID: ca2910ca6e71
Revises: 1dc1ecd24ea9
Create Date: 2026-07-22 11:17:47.492193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2910ca6e71'
down_revision = '1dc1ecd24ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('itens', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('taxa_entrega', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('distancia', sa.Integer(), nullable=True),
    sa.Column('tempo_entre_distancia', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_recebido', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
