"""criando tabela produtos com loja_id

Revision ID: e2a573ebf7fe
Revises: 
Create Date: 2025-12-10 09:59:03.967264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a573ebf7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celularp', sa.Integer(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('nomedaloja', sa.String(), nullable=True),
    sa.Column('nextreferencia', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('nome_produto', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_carrinho')
    op.drop_table('produto')
    op.drop_table('carrinho')
    op.drop_table('user')
    op.drop_table('store')
    # ### end Alembic commands ###
